# Generated by Django 4.0.2 on 2022-03-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0006_user_registration_hrmanager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tester_status',
            old_name='files',
            new_name='json',
        ),
        migrations.AddField(
            model_name='tester_status',
            name='json_testerscreenshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
